swagger: "2.0"
info:
  title: "OpenFisca France"
  description: "The OpenFisca API lets you get up-to-date information and formulas pertaining to the French legislation e.g. minimum wage, state scholasrship, social benefits, income taxes ..."
  version: "0.1.0"
  termsOfService: "https://doc.openfisca.fr/publishing.html"
  contact:
    email: "contact@openfisca.fr"
  license:
    name: "AGPL"
    url: "https://www.gnu.org/licenses/agpl-3.0.html"
host: "api-test.openfisca.fr"
schemes:
  - "https"
tags:
- name: "Parameters"
  description: "A parameter is a numeric property of the legislation which can evolve over time."
  externalDocs:
    description: "Find out more"
    url: "https://doc.openfisca.fr/parameters.html"
- name: "Variables"
  description: "A variable depends on a person, or an entity (e.g. zip code, salary, income tax)."
  externalDocs:
    description: "Find out more"
    url: "https://doc.openfisca.fr/variables.html"
paths:
  /parameters:
    get:
      tags:
      - "Parameters"
      summary: "List all available parameters"
      operationId: "getParameters"
      produces:
      - "application/json"
      responses:
        200:
          description: "The list of parameters is sent back in the response body"
          headers :
            Country-Package :
              description : "The name of the country package served by the API"
              type: "string"
            Country-Package-Version:
              description: "The version of the country package served by the API"
              type: "string"
          schema:
            $ref: '#/definitions/ListOfParam'
  /parameter/{parameterID}:
    get:
      tags:
      - "Parameters"
      summary: "Gets information about a specific parameter"
      operationId: "getParameter"
      produces:
      - "application/json"
      parameters:
      - name: "parameterID"
        in: "path"
        description: "ID of parameter (e.g. impot_revenu.bareme)"
        required: true
        type: "string"
      responses:
        200:
          description: "The requested parameter's information is sent back in the response body"
          headers :
            Country-Package :
              description : "The name of the country package served by the API"
              type: "string"
            Country-Package-Version:
              description: "The version of the country package served by the API"
              type: "string"
          schema:
            $ref: "#/definitions/Param"
        404:
          description: "The requested parameter does not exist"
          headers :
            Country-Package :
              description : "The name of the country package served by the API"
              type: "string"
            Country-Package-Version:
              description: "The version of the country package served by the API"
              type: "string"
  /variables:
    get:
      tags:
      - "Variables"
      summary: "List all available variables"
      operationId: "getVariables"
      produces:
      - "application/json"
      responses:
        200:
          description: "The list of variables is sent back in the response body"
          headers :
            Country-Package :
              description : "The name of the country package served by the API"
              type: "string"
            Country-Package-Version:
              description: "The version of the country package served by the API"
              type: "string"
          schema:
            $ref: "#/definitions/ListOfVars"
  /variable/{variableID}:
    get:
      tags:
      - "Variables"
      summary: "Gets information about a specific variable"
      operationId: "getVariable"
      produces:
      - "application/json"
      parameters:
      - name: "variableID"
        in: "path"
        description: "ID of a variable (e.g. aide_embauche_pme)"
        required: true
        type: "string"
      responses:
        200:
          description: "The requested parameter's information is sent back in the response body"
          headers :
            Country-Package :
              description : "The name of the country package served by the API"
              type: "string"
            Country-Package-Version:
              description: "The version of the country package served by the API"
              type: "string"
          schema:
            $ref: "#/definitions/Var"
        404:
          description: "The requested parameter does not exist"
          headers :
            Country-Package :
              description : "The name of the country package served by the API"
              type: "string"
            Country-Package-Version:
              description: "The version of the country package served by the API"
              type: "string"
definitions:
  Param:
    type: "object"
    properties:
      values:
        type: "object"
      description:
        type: "string"
      id:
        type: "integer"
        format: "string"

  ListOfParam:
    type: "object"
    additionalProperties:
      $ref: "#/definitions/Param"

  Var:
    type: "object"
    properties:
      defaultValue:
        type: "integer"
        format: "int64"
      definitionPeriod:
        type: "string"
      description:
        type: "string"
      entity:
        type: "string"
      formulas:
        type: "object"
      id:
        type: "string"
      reference :
        type: "array"
        items:
          type : "string"
      source :
        type: "string"
      valueType:
        type: "number"
        format: "float"

  ListOfVars:
    type: "object"
    additionalProperties:
      $ref: "#/definitions/Var"